### ISSUE TITLE
Ligar rede neural ao jogo

### ISSUE THREAD

**Issue by joaogsma** [rlfscin/bioinspirada#19]
Ligar a rede neural da classe "Individual" ao jogo, para que ela receba suas entradas do jogo e tome as decisões de quando pular.

**Comment by pedroneves** [comment]
Da maneira que eu vejo, teria que rodar a rede neural, medir o quao longe chegou e esse é o fitness.
A gnt tinha conversado sobre qual medida usar... Ficou definido o numero de loops do game, não foi?

**Comment by joaogsma** [comment]
É isso mesmo. O fitness seria (score, clocks), com clocks sendo usado para desempate quando o score for igual. O propósito desse issue é ligar a rede ao jogo, de modo que ela receba o estado do jogo como entrada e tome as decisões de pular ou não.
